#!/bin/bash
grim ~/Pictures/desktop.png
convert ~/Pictures/desktop.png -scale 5% -scale 2000% ~/Pictures/desktop.png
convert ~/Pictures/desktop.png -blur 0x8 ~/Pictures/desktop.png
swaylock -i ~/Pictures/desktop.png
