#!/bin/sh
CURRENT_SINK=$(pactl list short | grep RUNNING | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,')
if [ "$CURRENT_SINK" == "" ]; then
  CURRENT_SINK="0"
fi
pactl list sinks | perl -000ne 'if(/#'"${CURRENT_SINK}"'/){/(Volume:.*)/; print "$1\n"}' | awk '{print $5}'
